**COMP3670/6670 Introduction to Machine Learning** -- **Assignment 1**

**Deadline:** 23:59pm, August 11th, 2019

**Submit:** Write your answers in this file, and submit a single Jupyter Notebook file (.ipynb) on Wattle.

**Therom: 50%**

**Programming: 50%**

**Enter Your Student ID:**

**Name:**

As mentioned in course introduction, you are required to list all the students you discussed with for the assignment.

**The next cell** is for you to write down all of them using their University IDs.

Three examples for formatting is:

u1234567.

u1234567, u1234568.

u1234567, u1234568, u1234569.

u1234567, u1234568. (Replace this line with the IDs you discussed with during the assignment)

# Therom

Questions below are taken from 
the textbook *Mathematics for Machine Learning*,
https://mml-book.github.io/book/mml-book.pdf

Answer the below questions from the textbook.

- **2.4**  (a), (d) only
- **2.8**
- **2.9**
- **2.10**
- **2.11**
- **2.13**
- **2.16**  (b), (c), (d), (e) only
- **Q1** (not from the textbook) Find the set $\it{S}$ of all solutions $\bf{x}$ of the following inhomogeneous linear systems $\bf{Ax=b}$, where
$\bf{A}$ and $\bf{b}$ are defined as follows:

**a)**
$$\textbf{A} = 
\begin{bmatrix}
    3 & -1 & 11\\
    2 &  1 &  4\\
    1 &  0 &  3
\end{bmatrix}
, \quad \textbf{b} = 
\begin{bmatrix}
    10\\
     2\\
     6
\end{bmatrix}
$$

**b)**
$$\textbf{A} = 
\begin{bmatrix}
     2 &  -4 & 13\\
    -1 &   1 &  9\\
     3 & -10 & -9
\end{bmatrix}
, \quad \textbf{b} = 
\begin{bmatrix}
    -55\\
     41\\
    -26
\end{bmatrix}
$$

**c)**
$$\textbf{A} = 
\begin{bmatrix}
    1 & -1 & 1\\
    1 & -3 & 1\\
    2 &  1 & 2
\end{bmatrix}
, \quad \textbf{b} = 
\begin{bmatrix}
    11\\
    19\\
    10
\end{bmatrix}
$$

### <span style="color:blue">Answers</span>
<i>--- replace this with your solution, add and remove code and markdown cells as appropriate ---</i>

# Coding

**INTRO:**
---

**NOTE:** *This part of the first assignment is by necessity somewhat tedious as its primary purpose is to introduce syntax, how to access and understand the Numpy documentation and some very basic concepts. If you are already familiar with Numpy, you can just read the **TASK** headings and complete the questions without worrying about all the additional information. This is designed for people who have never seen Numpy before, so it's a very easy 1st year style introduction to just introduce syntax.*

*As this is a third year subject, it is assumed you already know to to program well (but may be unfamiliar with Python and Numpy).*

---

Arguably the most fundamental tool needed to engage with machine learning in Python is Numpy *(np)*. To include Numpy in any project, simply type the following line at the top of your python file:

**Marking distribution for the homework/assignment**

EX1 = 5%

EX2 = 10%

EX3 = 10%

EX4 = 75%

In [9]:
import numpy as np

print('Done')

Done


A Jupyter Notebook is divided into cells, each of which works like a Python module or Latex file. When a cell is run, any cells that follow it will have access to its results. Running the above cell will give all following cells access to the Numpy library.

-----------

   **TASK 0.1:** To run the above cell, select it by clicking on it, hold **shift** and press **return**. If you have succeeded, then the cell will print "Done" just above.


-----------

Numpy is a library of common mathematical data structures and algorithms used in machine learning. For example:

- It allows you to declare vectors and matrices, with all the associated mathematical operations like matrix vector products, matrix addition / subtraction.
- It provides convenient, efficient implementations of algorithms to solve matrix equations, find the inverse of a matrix or perform Eigen decomposition. The implementation of these algorithms is compiled from C code, making Numpy much faster than programming these algorithms yourself in Python.

You'll need to know Numpy inside and out. We'll start by getting you familiar with the easy to access online documentation and performing a few basic operations.

Below I have declared the matrices: 

$$A = 
\begin{bmatrix}
2&3\\
0&1\\
\end{bmatrix}
\\
x = 
\begin{bmatrix}
1\\
3\\
\end{bmatrix}
$$. 

---
**TASK 0.2:** Run the cell below and observe what it prints.


---
(If it throws an error, you have the wrong version of python installed. This entire course will use Python 3, not Python 2)



In [10]:
A = np.array([[2, 3], [0, 1]])
x = np.array([[1], [3]])

#Matrix Multiplication Example
b = A @ x
print('\nMatrix Multiplication')
print(b)


Matrix Multiplication
[[11]
 [ 3]]


The above code illustrates how to perform matrix multiplication. Memorise it. Below are some other basic operations you'll likely need over the coming semester:

In [11]:
#Matrix Addition Example
b = A + x
print('\nMatrix Addition')
print(b)

#Elementwise Multiplication Example
b = A * x
print('\nElementwise Matrix Multiplication')
print(b)

#Extract a single element of a matrix:
print('\nSingle Element Extraction')
b = A[0, 0]
print(b)

#Extract an entire column of a matrix:
print('\nColumn Extraction')
b = A[:, 0]
print(b)

#Extract an entire row of a matrix:
print('\nRow Extraction')
b = A[0, :]
print(b)

#Transpose of a matrix:
print('\nTranspose')
A_Transpose = A.T
print(A_Transpose)


Matrix Addition
[[3 4]
 [3 4]]

Elementwise Matrix Multiplication
[[2 3]
 [0 3]]

Single Element Extraction
2

Column Extraction
[2 0]

Row Extraction
[2 3]

Transpose
[[2 0]
 [3 1]]






**EXERCISE 1**
---

We're now going to compute the inverse of $A$. 

---
**TASK 1.1:** Use Numpy's inverse function (see link below) to compute this inverse.

---

https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html

Read the documentation and use the described function to compute the inverse of $A$, the matrix declared earlier.

In [4]:
A = np.array([[2, 3], [0, 1]])

A_inv = #YOUR CODE HERE

print(A_inv)

SyntaxError: invalid syntax (<ipython-input-4-8e289757d260>, line 3)

Great! Assuming your above code is correct, you now know how to compute an inverse in Python.

Below is a vector $b$, computed using $Ax = b$, with an unknown $x$.

---
**TASK 1.2:** Use the inverse of $A$ to determine $x$.

---

In [ ]:
b = np.array([[3], [5]])

x = #YOUR CODE HERE

print(x)


---
**TASK 1.3:** Now verify your answer by finding $x$ using Numpy's solve function.

---

https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html

In [ ]:
x = #YOUR CODE HERE

print(x)

 Good work. But what if we're trying to solve for a matrix without an inverse? Numpy's solve function won't work in that case.





**EXERCISE 2**
---

Below I've declared a new version of $b$, and a new version of $A$ with no inverse. 

---

**TASK 2.1:** $Ax = b$, where we know only $A$ and $b$. Solve for $x$.

---
**NOTE:** You **should not** use the Numpy function for **pseudo** inverse linalg.pinv() for **TASK 2.1**. The point is to verify you understand how to compute the pseudo inverse yourself.

Because $A$ has no inverse, we need to compute its pseudo inverse, also known as the Moore-Penrose inverse. This is covered in detail in your textbook, however in case you need a reminder, here's the Wikipedia page. Good rule of thumb to live by; if you're unsure of what something is, check Wikipedia, and check the Numpy documentation. Failing that, check Stack Overflow.

https://en.wikipedia.org/wiki/Moore–Penrose_inverse



In [ ]:
A = np.array([[1, 3], [2, 7], [5, 1]])
b = np.array([[13], [30], [9]])

A_pseudo_inverse = #YOUR CODE HERE
x = #YOUR CODE HERE

print(x)

**TASK 2.2:** Now use the Numpy pseudo inverse to find $x$ and verify your answer is correct (you should get the same result as 2.1).

https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.linalg.pinv.html


In [ ]:
A_pseudo_inverse = #YOUR CODE HERE
x = #YOUR CODE HERE

print(x)

**EXERCISE 3**
---

Now we're going to learn to visualise data. We'll start by visualising the 2 column vectors which make up the matrix $A$ above.

Every matrix can be thought of as a sequence of column or row vectors. Generally speaking, because of the manner in which matrix multiplication works, people refering to the vectors which make up a matrix are often refering to the rows of the matrix. However changing between the two just requires you transpose the matrix.

---
**TASK 3.1:** Look up np.random.eye(), and use it generate a 2 by 2 identity matrix $I = 
\begin{bmatrix}
1&0\\
0&1\\
\end{bmatrix}
$.

---

**TASK 3.2:** Plot arrows representing the 2 column vectors of the identity matrix $I$ in 2d space, such that it looks like the image below. Part of the code has been filled in for you.

---

![title](eye.png)


**HINTS:** 
- You'll need to use plt.quiver() with angles='xy', scale_units='xy' and scale=1. 
    - https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.quiver.html
- You'll need use '*origin' as the origin of the quiver plot, including the asterix.
- You'll need to use plt.xlim and .ylim with limits -2 and 2.
    - https://matplotlib.org/api/_as_gen/matplotlib.pyplot.xlim.html
    - https://matplotlib.org/api/_as_gen/matplotlib.pyplot.ylim.html
- You'll need to follow these statements with plt.show().
    - https://matplotlib.org/api/_as_gen/matplotlib.pyplot.show.html

In [ ]:
import matplotlib.pyplot as plt

origin = [0], [0]

I = #YOUR CODE HERE
plt.quiver(*origin, , , , , )

---
**TASK 3.3:** Generate a 1000 by 2 matrix of 1000 2-dimensional samples with np.random.randn(), and plot these with plt.plot(). 

---

In [ ]:
#YOUR CODE HERE

**EXERCISE 4**
---

---
**TASK 4.1:** Implement a function that reduces any matrix to reduced row echelon form, and apply it to reduce the following matrix $A$ to reduced row echelon form. You must implement the gaussian elimination algorithm yourself, not merely call someone elses library function.

---

**HINT:** https://en.wikipedia.org/wiki/Gaussian_elimination

In [ ]:
A = np.array([[1, 0, 1, 1],
             [1, 0, 1, 1],
             [0, 1, 1, 1],
             [1, 1, 1, 0],
             [1, 1, 1, 0]])

def gaussian_elim(A):
    #YOUR CODE HERE
    return A

print(gaussian_elim(A))

Use the code below to verify your result.

In [ ]:
import sympy as sp
disp_A = np.array(sp.Matrix(A).rref()[0])
print(disp_A)

---
**TASK 4.2:** Implement a function that finds an orthonormal basis of *column* vectors for $A$. As with 4.1, you must implement the algorithm yourself. You may however use your Gaussian Elimination function, if you choose to implement a solution that depends upon Gaussian Elimination. Note that there are multiple solutions, only one of which requires gaussian elimination.

A link to the Gram-Schmidt algorithm is given to help you.

---

**HINT:** https://en.wikipedia.org/wiki/Gram–Schmidt_process

In [ ]:
def gram_schmidt(A):
    #YOUR CODE HERE
    return A

print(gram_schmidt(A))

---
**TASK 4.3:** Implement a function that accepts a matrix and returns TRUE if all the columns of that matrix are orthogonal to one another, and each one of them is of length 1 (the L2 norm of each column vector is 1).

Use this function to verify the output of your gram_schmidt function is an orthonormal basis for $A$.

Again, you must program this function yourself, rather than relying on a library function.

---

**HINT:** 
- A pair of column vectors $v_1$ and $v_2$ are orthogonal to one another if and only if $v_1^Tv_2 = 0$. They form an orthonormal basis if they are all orthogonal to eachother, and they are each of length 1. https://en.wikipedia.org/wiki/Orthogonality
- You can check whether your algorithms work using the last 6 lines in the code given below.

In [ ]:
def orthogonality_checker(A):
    is_orthogonal = False
    #YOUR CODE HERE
    return is_orthogonal

print(orthogonality_checker(gram_schmidt(A)))


true_test = np.eye(3,3)
false_test = np.ones((3,3))
print('\nCHECKING TRUE TEST (SHOULD RETURN TRUE):')
print(orthogonality_checker(true_test))
print('\nCHECKING FALSE TEST (SHOULD RETURN FALSE):')
print(orthogonality_checker(false_test))